name = "gp300"
main = "src/worker.py"
workers_dev = true
preview_urls = true
compatibility_flags = ["python_workers"]
compatibility_date = "2026-03-03"

[assets]
directory = "./public"

[[d1_databases]]
binding = "DB"
database_name = "gp300"
database_id = "8cf94e95-0310-4a7a-98b6-0430c799c27d"

[[kv_namespaces]]
binding = "CACHE_GP300"
id = "9200bf3e4ca3461785d49285dded428a"

[triggers]
crons = ["*/5 * * * *", "0 0 * * SUN", "0 0 1,15 * *"]

[observability]
[observability.logs]
enabled = true
invocation_logs = true